services:
  oauthbin:
    image: jondotsoy/oauthbin
    build: 
      context: .
      target: prod
    ports:
      - 4321:4321
    volumes:
      - data:/data
    deploy:
      resources:
        limits:
          memory: 64M
    # command: sleep 5000

volumes:
  data: {}
